### ISSUE TITLE
It seems that when trying to pass the --xformers flag for the training process using the i2vgen-XL model it erros.

### ISSUE THREAD

**Issue by wisleythewise** [HL-hanlin/Ctrl-Adapter#14]
```
total_trainable_params_count is:  587346458
  0%|             | 0/9999999 [00:00<?, ?it/s]/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/torch/nn/modules/conv.py:605: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv3d(
Traceback (most recent call last):
  File "/home/wisley/Ctrl-Adapter/train.py", line 1531, in <module>
    main(args)
  File "/home/wisley/Ctrl-Adapter/train.py", line 1504, in main
    process_batch(batch)
  File "/home/wisley/Ctrl-Adapter/train.py", line 1459, in process_batch
    loss, down_block_weights, mid_block_weights, lr_scheduler = process_batch_func(batch)
  File "/home/wisley/Ctrl-Adapter/train.py", line 1437, in process_batch_func
    loss, down_block_weights, mid_block_weights = compute_loss_from_batch(batch)
  File "/home/wisley/Ctrl-Adapter/train.py", line 1348, in compute_loss_from_batch
    model_pred = unet(
  File "/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/accelerate/utils/operations.py", line 822, in forward
    return model_forward(*args, **kwargs)
  File "/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/accelerate/utils/operations.py", line 810, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/wisley/Ctrl-Adapter/i2vgen_xl/models/unets/unet_i2vgen_xl.py", line 650, in forward
    image_latents = self.image_latents_temporal_encoder(image_latents)
  File "/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wisley/Ctrl-Adapter/i2vgen_xl/models/unets/unet_i2vgen_xl.py", line 91, in forward
    attn_output = self.attn1(norm_hidden_states, encoder_hidden_states=None)
  File "/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 522, in forward
    return self.processor(
  File "/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 1191, in __call__
    hidden_states = xformers.ops.memory_efficient_attention(
  File "/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 268, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 387, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 403, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp, False)
  File "/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 125, in _dispatch_fw
    return _run_priority_list(
  File "/root/miniconda3/envs/ctrl-adapter/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 65, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(8192, 10, 1, 4) (torch.bfloat16)
     key         : shape=(8192, 10, 1, 4) (torch.bfloat16)
     value       : shape=(8192, 10, 1, 4) (torch.bfloat16)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`decoderF` is not supported because:
    attn_bias type is <class 'NoneType'>
`flshattF@v2.5.6` is not supported because:
    query.shape[-1] % 8 != 0
`cutlassF` is not supported because:
    query.shape[-1] % 8 != 0
    value.shape[-1] % 8 != 0
`smallkF` is not supported because:
    dtype=torch.bfloat16 (supported: {torch.float32})
    has custom scale
```

**Comment by wisleythewise** [comment]
Sorry my bad I have incompatible NVIDEA drivers installed

**Comment by abcdvzz** [comment]
Hi How did you solve the problem? I met the same issue.
